blogwebsite/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import home, about, contact
from registrar.views import signin, signout, register

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('register/', register, name='register'),
    path('signin/', signin, name='signin'),
    path('signout/', signout, name='signout'),
    path('about/', about, name='about'),
    path('contact/', contact, name='contact'),
    path('submit_news/', include('news.urls', namespace='news'))
]

news/urls.py
from django.urls import path
from .views import submit_news, submit_category

app_name = 'news'


urlpatterns = [
    path('submit_news/', submit_news, name='submit_news'),
    path('submit_category/', submit_category, name='submit_category'),
]

news/models.py
from turtle import title
from unicodedata import category
from django.db import models
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager,
                    self).get_queryset()\
                    .filter(publish=True)

class Category(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

# Create your models here.
class News(models.Model):
    title = models.CharField(max_length=200)
    body = models.TextField()
    author = models.ForeignKey(User, on_delete=models.DO_NOTHING, related_name='news_user')
    category = models.ForeignKey(Category, on_delete=models.DO_NOTHING, related_name='news_category')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    slug = models.SlugField(max_length=250)
    publish = models.BooleanField()
    objects = models.Manager()

    published = PublishedManager()

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(News, self).save(*args, **kwargs)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return self.title

registrar/models.py
from django.db import models

# Create your models here.

news/forms.py
from django import forms
from .models import News, Category

class NewsForm(forms.ModelForm):
    class Meta:
        model = News
        fields = ['title','body','author', 'category', 'publish']

class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = '__all__'

registrar/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm



class RegisterForm(UserCreationForm):
    
    def __init__(self, *args, **kwargs):
        super(RegisterForm, self).__init__(*args, **kwargs)

    class Meta:
        model = User
        # fields = ['nome', 'cpf', 'dt_nascimento', 'email', 'sexo', 'slug', 'usuario', 'cadastrado_por']
        fields = ['username', 'first_name', 'last_name', 'email', 'password1', 'password2']


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget = forms.PasswordInput)

blogwebsite/views.py
from django.shortcuts import render, redirect

from news.models import News

def home(request):
    if not request.user.is_authenticated:
        return redirect('/signin/')

    news = News.published.all()

    return render(request, 'home.html', {'news': news})


def about(request):
    if not request.user.is_authenticated:
        return redirect('/signin/')

    return render(request, 'about.html', {})


def contact(request):
    if not request.user.is_authenticated:
        return redirect('/signin/')

    return render(request, 'contact.html', {})

news/views.py
from django.shortcuts import render, redirect
from .forms import NewsForm, CategoryForm
from .models import News, Category
from django.core.cache import cache
from django.core.mail import EmailMessage

def send_email(request, author_email):
    msg = EmailMessage('Congrats! New Article',
                       'You just submitted a new article at your blog!', to=[author_email])
    msg.send()
    return redirect('/')



# Create your views here.
def submit_news(request):
    form = NewsForm()

    if request.method == 'POST':
        form = NewsForm(request.POST)
        if form.is_valid():
            newNews = News.objects.create(
                title = form.cleaned_data['title'],
                body = form.cleaned_data['body'],
                author = form.cleaned_data['author'],
                publish = form.cleaned_data['publish'],
                category = form.cleaned_data['category'],
            )

            newNews.save()
            print(request.user.email)
            send_email(request, request.user.email)
            cache.clear()
        return redirect('/')
    return render(request, 'submit_news.html', {'form':form})


def submit_category(request):
    form = CategoryForm()

    if request.method == 'POST':
        form = CategoryForm(request.POST)
        if form.is_valid():
            newCategory = Category.objects.create(
                name = form.cleaned_data['name'],
            )

            newCategory.save()
            cache.clear()
        return redirect('/')
    return render(request, 'submit_category.html', {'form':form})

registrar/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from .forms import RegisterForm, LoginForm

# Create your views here.
def register(request):
    form = RegisterForm()
    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            newUser = User.objects.create(
                username = form.cleaned_data["username"],
                first_name = form.cleaned_data["first_name"],
                last_name = form.cleaned_data["last_name"],
                email = form.cleaned_data["email"],
            )
            newUser.set_password(form.cleaned_data["password1"])
            newUser.save()

    return render(request, 'register.html', {'form': form})

def signin(request):
    
    user_form = LoginForm()
    if request.method == 'POST':
        user_form = LoginForm(request.POST)
        
        if user_form.is_valid():            
            username = user_form.cleaned_data['username']
            password = user_form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('/')

    return render(request, 'signin.html', {'form':user_form})


def signout(request):
    logout(request)
    return redirect('/')

news/templates/submit_category.html
{% extends 'base.html' %}

{% block title %}
Adding Category
{% endblock %}



{% block content %}
    {% include 'navbar.html' %}
<div class="container d-flex">
    
    <form class="well" method="POST">
        {% csrf_token %}
        {{form}}
        <div>
        <button type="submit" class="btn btn-primary btn-large">Save</button>
    </div>
    </form>

</div>
{% endblock %}

news/templates/submit_news.html
{% extends 'base.html' %}

{% block title %}
Adding News
{% endblock %}



{% block content %}
    {% include 'navbar.html' %}
<div class="container d-flex">
    
    <form class="well" method="POST">
        {% csrf_token %}
        {{form}}
        <div>
        <button type="submit" class="btn btn-primary btn-large">Save</button>
    </div>
    </form>

</div>
{% endblock %}

registrar/templates/register.html
{% extends 'base.html' %}

{% block title %}
Register
{% endblock %}



{% block content %}
{% include 'navbar.html' %}
<div class="container d-flex">
    <form class="form-horizontal well" method="POST">
        {% csrf_token %}
        {{form}}
        <div>
        <button type="submit" class="btn btn-primary btn-large">Register</button>
    </div>
    </form>

</div>
{% endblock %}

registrar/templates/signin.html
{% extends 'base.html' %}

{% block title %}
Sign-in
{% endblock %}



{% block content %}
<div class="container">
    <form class="form-horizontal well" method="POST">
        {% csrf_token %}
        {{form}}
        <div>
        <button type="submit" class="btn btn-primary btn-large">Sign-in</button>
    </div>
    </form>

</div>
{% endblock %}

templates/about.html
{% extends 'base.html' %}

{% block title %}
Home
{% endblock %}

{% block content %}
    {% include 'navbar.html' with page="2" %}

  <div class="container">

    <!-- Main hero unit for a primary marketing message or call to action -->
    <div class="hero-unit">
      <h1>Hello, I'm {{request.user.first_name}}!</h1>
      <h2>'Gonna tell you a little bit about myself!</h2>
      <p style="margin-top:10pt; text-align: justify;">Meu nome é Lucas Amaral, 23 anos de idade cursando os últimos períodos de Ciência da Computação na Universidade Federal Fluminense. Já trabalhei com programação Front-End com React Native e com manutenção de aplicação WEB para contratos de crédito imobiliário com a empresa Prognum.
        Já trabalhei na incubadora de StartUps da UFF sob orientação do professor Francisco Souza.
        Já tive contato com as principais linguagens do mercado como Python, Java, C, Javascript. Já fiz manutenção em bancos da ORACLE, MSSQL e Interbase durante meu período na Prognum(2019-2021).
        Também atuei como desenvolvedor React Native para aplicativos móveis no laboratório LMDC da UFF(2020-2021).
        Atualmente atuo como Engenheiro de Dados em um projeto da Fiocruz. O trabalho consiste em integrar, limpar, transformar e analisar dados de diversas fontes da Fiocruz elaborado por distintos laboratórios utilizando técnicas ETL com Python, diversas bases de dados, e ferramentas como Knime Analitcs Platform e Apache.
        Estou em busca de oportunidades que me permitam usar meus conhecimentos obtidos ao longo da vida acadêmica para solucionar problemas e adquirir experiência profissional. Dessa forma, tenho como objetivo crescer junto com a empresa e agregar valor a mesma.
        Gosto de viajar, já estive em muitos lugares da América e Europa o que me levou ao interesse de aprender línguas. Fiz intercâmbio para aprender espanhol na Argentina pelo curso HIBRA em 2017. Me comunico em Inglês muito bem já tendo feito o curso HI. Além disso, fiz dois níveis de Francês no programa da UFF Prolem.</p>
    </div>


    <hr>

    <footer>
      <p>&copy; Company 2022</p>
    </footer>

  </div>
{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}" />
    <title>
        {% block title %}
        Document
        {% endblock %}
    </title>
</head>
<body>

    {% block content %}

    {% endblock %}
    <script src="{% static 'js/bootstrap.js' %}"></script>
</body>
</html>

templates/card/card.html
<div class="span4">
    <h2>{{new.title}}</h2>
    <h4>{{new.author.first_name}} {{new.author.last_name}}</h4>
    <p>{{new.created}}</p>
     <p>{{new.body}}</p>
    <p><a class="btn" href="#">View details &raquo;</a></p>
</div>

templates/contact.html
{% extends 'base.html' %}

{% block title %}
Contact
{% endblock %}

{% block content %}
    {% include 'navbar.html' with page="3" %}

  <div class="container">

    <!-- Main hero unit for a primary marketing message or call to action -->
    <div class="hero-unit">
      <h1>Contact us, {{request.user.first_name}}!</h1>
      <p>Contact me and (hire me)!</p>
    </div>

    <hr>

    <footer>
      <p>&copy; Company 2022</p>
    </footer>

  </div>
{% endblock %}

templates/home.html
{% extends 'base.html' %}

{% block title %}
Home
{% endblock %}

{% block content %}
    {% include 'navbar.html' with page="1" %}

  <div class="container">

    <!-- Main hero unit for a primary marketing message or call to action -->
    <div class="hero-unit">
      <h1>Hello, {{request.user.first_name}}!</h1>
      <p>In this website you can write your piece and publish it in this page. Checkout the top right option on the navbar! Beware to register and login first!</p>
    </div>

    <!-- Example row of columns -->
    <div class="row">
      {% for new in news %}
        {% include 'card/card.html' with new=new%}
      {% endfor %}
    </div>

    <hr>

    <footer>
      <p>&copy; Company 2022</p>
    </footer>

  </div>
{% endblock %}

templates/navbar.html
<div class="navbar">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <a class="brand" href="#">Blog Website</a>
        <div class="nav-collapse">
          <ul class="nav">
            <li {% if page == '1' %}class="active"{% endif %}><a href="{% url 'home' %}">Home</a></li>
            <li {% if page == '2' %}class="active"{% endif %}><a href="{% url 'about' %}">About</a></li>
            <li {% if page == '3' %}class="active"{% endif %}><a href="{% url 'contact' %}">Contact</a></li>
          </ul>
        </div><!--/.nav-collapse -->
        <div class="nav-collapse" style="float: right">
          <ul class="nav">
            <li class="active"><a href="{% url 'news:submit_news' %}">Add News</a></li>
            <li class="active"><a href="{% url 'news:submit_category' %}">Add Category</a></li>
            <li class="active"><a href="{% url 'register' %}">Register Author</a></li>
            <li class="active"><a href="{% url 'signout' %}">Logout</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>
  </div>